version: '3.8'
services:
  kp-tasks-postgres-db:
    image: 'postgres:latest'
    container_name: kp-tasks-postgres-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=tasksdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
    volumes:
      - tasks-postgres-db-data:/data/db

  kp-tasks-service:
    build: .
    image: 'kp-tasks-service:0.1.0-SNAPSHOT'
    container_name: kp-tasks-service
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=kp-tasks-postgres-db
      - DB_PORT=5432
      - DB_NAME=tasksdb
      - DB_USERNAME=user
      - DB_PASSWORD=secret
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - kp-tasks-postgres-db

  kp-tasks-prometheus:
    image: prom/prometheus
    container_name: kp-tasks-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  kp-tasks-tempo:
    image: grafana/tempo
    container_name: kp-tasks-tempo
    restart: unless-stopped
    ports:
      - "14268"  # Jaeger
      - "9411:9411" # Zipkin
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo.yaml:/etc/tempo.yaml:ro
      - tasks-tempo-data:/tmp/tempo

  kp-tasks-loki:
    image: grafana/loki
    container_name: kp-tasks-loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    depends_on:
      - kp-tasks-tempo

  kp-tasks-grafana:
    image: grafana/grafana
    container_name: kp-tasks-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
      - ./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    depends_on:
      - kp-tasks-loki
      - kp-tasks-prometheus

volumes:
  tasks-postgres-db-data:
  tasks-tempo-data:
