#!/usr/bin/env bash

echo "Checking commit message:"

# Create a regex for a conventional commit
conventional_commit_regex="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z \-]+\))?!?: .+$"

# Get the commit message
commit_message=$(cat "$1")

# Check the message
if [[ "$commit_message" =~ $conventional_commit_regex ]]; then
   echo -e "\e[32mCommit message meets Conventional Commit standards...\e[0m"
   echo ""
   exit 0
fi

# The commit is does not follow the convention, show an example and link to the spec.
echo -e "\e[31mThe commit message does not meet the Conventional Commit standard\e[0m"
echo "The message must follow the following regex: "
echo "$conventional_commit_regex"
echo "An example of a valid message is: "
echo "  feat(login): add the 'remember me' button"
echo "More details at: https://www.conventionalcommits.org/en/v1.0.0/#summary"
echo ""
exit 1